### ISSUE TITLE
Bug: `Add Lifeblood` conflicts with shell binding

### ISSUE THREAD

**Issue by Clazex** [Clazex/HollowKnight.GodSeekerPlus#14]
To replicate, load a save with shell bound by `ToggleableBindings`, then fight any boss.
The `Blue Health Control` FSM of `_GameCameras/HudCamera/Hud Canvas/Health` in `DontDestroyOnLoad` stuck in `Wait` state.

**Comment by TheMulhima** [comment]
Why would this be the case?

**Comment by Clazex** [comment]
> Why would this be the case?

Practising AB

**Comment by Clazex** [comment]
Propagated to Unordinal/HollowKnight.ToggleableBindings#5
