### ISSUE TITLE
Lifeblood sometimes not added when entering pantheon segments

### ISSUE THREAD

**Issue by royitaqi** [Clazex/HollowKnight.GodSeekerPlus#28]
I have ToggleableBindings and chose all bindings. Then I enter segments provided by GodSeekerPlus, e.g. starting with Hive Knight or Watch Knights. Sometimes, the lifeblood isn't applied as I enter the segments. And once it doesn't apply, subsequent runs also don't have that lifeblood. Similar thing sometimes happens in HoG, where I pick one boss to challenge.

I verified that in the GodSeekerPlus.GlobalSettings.json file, the lifeblood is set to 5.
Restarting the game doesn't always fix this problem.
Turning the mod on/off doesn't always fix this problem.

**Comment by Clazex** [comment]
This is a bug of Toggleable Bindings, see #14
Current solution: 1. Use vanilla bindings 2. Remove Shell binding before quiting and re-enter save
