### ISSUE TITLE
Feature Request: Separated Halve Damage & grouped module toggle

### ISSUE THREAD

**Issue by royitaqi** [Clazex/HollowKnight.GodSeekerPlus#29]
To practise p5ab (p5 being the same I assume), I often go into this workflow: try a segment (gj GodSeeker+ !), find out that I suck at a boss, go into HoG to practise that boss in ascended difficulty with "Half Damage" to simulate the p5 configuration.

The problem is (to be clear it might not be a problem of the mod, but maybe how I'm using it) that when I have done that per-boss practice and go back to attempt the segment, I have to turn off "Half Damage", because otherwise it makes certain boss do less dmg (Enraged Guardian, NMG, PV, AbsRad, etc).  So if one follows up workflow above, they will need to turn the feature on->off->on->off->...

I wonder if the feature is only useful when fighting ascended boss in HoG trying to simulate p5ab (p5, similarly). If that's the case, maybe the mod can detect that the player is in HoG fight and only apply the feature in this case. This will allow the user to not having to turn it on/off back and forth.

LMK if this makes any sense.

---

An alternative is a quick toggle menu for some of the handy features that needs flipping: lifeblood, half dmg, boss hp.

**Comment by Clazex** [comment]
Would it be good to separate Halve Damage into different features that function at different time? (e.g. one HoG only, one Pantheons only, one other place only)

**Comment by royitaqi** [comment]
I like your idea. This way (1) the user doesn't have to toggle anything at all; (2) it's clear what is done where/when.

Just my 2cent:
- Half Damage: HoG (I cannot think of why Half Damage is useful in Pantheons)
- Attuned Boss HP: HoG (Same, I feel Attuned Boss HP is only useful in HoG when simulating p5 fights)
- Random thought: Maybe combine the above two into "Turn Ascended fight into P5 fight".
- Lifeblood: HoG, Pantheons, other place (BTW, what's "other place"? There is only HoG and Pantheons in Godhome, right?)

**Comment by royitaqi** [comment]
> Afaik there are some people using this in the overworld.
K that make sense. Thanks for considering and implementing this. Big help!
