### ISSUE TITLE
Bug: Toggling `Halve Damage` and `P5 Health` require restart to take effect

### ISSUE THREAD

**Issue by TheSessa** [Clazex/HollowKnight.GodSeekerPlus#40]
This seems to be a common problem since I've seen a few people asking about the same thing. After installing GodSeekerPlus and toggling the halve damage and p5 health settings, the damage and hp values don't apply in the HoG, until you restart the game once. After that, they seem to work (unless you uninstall and reinstall the mod again). Obviously not a big issue but it's confusing to people who don't know restarting works.

**Comment by Clazex** [comment]
I cannot reproduce this on my side, toggling them takes effect immediately without needing a restart.
There are cases when Scarab forget to update dependencies (`Satchel`, `Osmi` & `HKMirror`), try uninstall-reinstall in Scarab first.
If the problem persist, you can post your `ModLog.txt` here for more debug information

**Comment by TheSessa** [comment]
Hmm interesting, the settings take effect immediately now for me too. The reason I posted was because I've helped at least two other runners with this problem before, and I used to have this issue earlier as well. Maybe it was the dependencies that weren't updated. Thanks for your helps and sorry for the trouble!
