### ISSUE TITLE
Bug in mod: half health Hall of Gods Ascended difficulty not working

### ISSUE THREAD

**Issue by PietJanHein** [Clazex/HollowKnight.GodSeekerPlus#45]
I installed a few mods via the currently latest version of Scarab: v1.34.0.0, including the GodSeekerPlus mod. The toggleable bindings mod works fine (I can turn on and off bindings by pressing crystal-dash+down) but there seems to be a problem with the GodSeekerPlus-mod, I still get 2 damage in the fight against the Collector in the Hall of Gods at ascended difficulty when I turn on this setting: "Boss Challenge" => "halve damage (HoG ascended or above)", as it is when this mod is turned off. I tried to toggle the setting while in-game and also restart the game after toggling the setting just in case but whatever I do, the setting does not work. 
The only mods which I have turned on are these two mods (and dependencies of course which are automatically turned on), so it seems that there is a bug in the current version of the mod. 

I attached two screenshots: one on which you see the setting being turned on and some data which Scarab gives in-game and the other showing which mods I have installed via Scarab and which are turned on. 
![hk1](https://github.com/Clazex/HollowKnight.GodSeekerPlus/assets/38538461/f2333ccd-cd15-4e84-859e-9d995d4bebde)
![hk2](https://github.com/Clazex/HollowKnight.GodSeekerPlus/assets/38538461/441a4ad4-d4a9-46ef-99bd-e6b1c4a7dce0) 

Additional information: I run the game Linux via Proton, so the game uses exactly the same files as on Windows. 
See the 3rd attached screenshot which shows the toplayer of the Hollow Knight Directory under Steam. 
![hk3](https://github.com/Clazex/HollowKnight.GodSeekerPlus/assets/38538461/d15ecd80-fa6f-4ad0-ae45-7a50dd3c67c9)
The game works 100% fine without the mods and as I pointed out, the toggleable bindings mod works exactly as it should so it is very unlikely that Proton or Linux has anything to do with this option of the GodSeekerPlus mod not working.

**Comment by DwarfWoot** [comment]
- mod must be turned on in the mods menu, in case it's off (this seems to be the case based on it not showing in your Mods List at the top-left of the paused screen)
- the game needs restarted after changing the settings for many of them to take effect

**Comment by PietJanHein** [comment]
> * mod must be turned on in the mods menu, in case it's off (this seems to be the case based on it not showing in your Mods List at the top-left of the paused screen)
> 
>     * the game needs restarted after changing the settings for many of them to take effect

Thanks! That indeed was the problem. In retrospect I was confused about this for 2 reasons: I assumed that turning on the mod in the modmanager (Scarab) would automatically turn it on (a bad assumption from me), also because the other mod was automatically turned on. The text under the toggle was a bit confusing to me, it implied to me that all the effects of the mod would be turned on. "Toggle all effects of this mod on", I interpreted that as literally turning on all the effects, not enabling the toggle of all the effects. That might be my wrong interpretation, I just elaborate on it to explain the confusion. Now it makes sense to me that you built in an on/off toggle for the mod inside the game given the number of settings, I didn't consider that before. Your mod is of great help for practicing P5 with all bindings on. 
![image](https://github.com/Clazex/HollowKnight.GodSeekerPlus/assets/38538461/0fc1ec89-28b2-4358-b54b-f3832fe0f104)
