### ISSUE TITLE
Enhancemant: Better ModMenu Pages

### ISSUE THREAD

**Issue by TheMulhima** [Clazex/HollowKnight.GodSeekerPlus#9]
Since there are 18 modules now (assuming you accept my pr #10) I suggest making the main page with only buttons that link to other pages with the actual options
[For example, see this](https://drive.google.com/file/d/1qg1fQ2Wljjw66m5vWmexdZ_zx4K33xim/view?usp=sharing)
this would make it less daunting to choose what people want to choose and also help categorize the options

The problem with this is that `IMenuMod` would not be able to be used. Instead, we would have to use `ICustomMenuMod`. To simplify that, I would suggest to using [Satchel's](https://github.com/PrashantMohta/Satchel/) `BetterMenus` to construct the pages and toggles.

**Comment by Clazex** [comment]
Implemented in ae7707e
